name: CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Client Dependencies
      working-directory: ./client
      run: npm install

    - name: Build Client
      working-directory: ./client
      run: npm run build

    - name: Install Server Dependencies
      working-directory: ./server
      run: npm install
